// src/pages/Blog.vue
<template>
  <Layout>
      <Title/>
    <div id="blog-page">
      <div id="blog-post-wrapper">
        <Blogposts :posts="posts" />
      </div>
    </div>
  </Layout>
</template>

<page-query>
query Posts {
  posts: allPost(filter: { published: { eq: true }}) {
    edges {
      node {
        id
        title
        date
        description
        path
        excerpt
        published
        tags {
          title
        }
    }
  }
  }
  }
  </page-query>

<script>
import mainImage from "../assets/img/blog_main.jpeg";
import Blogposts from "../components/Blogposts";
import Title from "../components/BlogTitle.vue";


export default {
  name:"Blog",
  metaInfo: {
    title: "Nate Spilman | Personal and Professional Website",
  },
  components: {
    Blogposts,
    Title
  },
  data() {
    return {
      mainImage,
    };
  },
  computed: {
    posts() {
      return this.$page.posts.edges;
    },
  },
};
</script>

<style scoped>
#blog-page {
  display:flex;
  flex-direction: column;
  padding:1rem 3rem;
}

</style>

// src/pages/blog.tsx
import React from "react"
import { graphql } from "gatsby"
import Post from "../components/postCard";
import SEO from "../components/seo"

import Layout from "../components/layout"

const Blog = ({ data }) => {
  const { blog } = data;
  const posts = blog.edges.map(post => post.node)

  return (
    <Layout>
      <SEO title="Nate's Blog"/>
      {/* <Title /> */}
      <div id="blog-page">
        <div id="blog-post-wrapper">
          <article id="blog" className="panel special">
            <div className="content">
              <h1>The Blog</h1>
              <div className="card-blog-container">
                {posts.map(post => <Post post={post} key={post.id}/>)}
              </div>
            </div>
          </article>
        </div>
      </div>
    </Layout>
  )
}

export const query = graphql`
  query AllBlogPosts {
    blog: allMarkdownRemark(
      sort: {fields: frontmatter___date, order: DESC}
    filter: { fields: { collection: { eq: "blog" } }}) {
    edges {
      node {
        id
        fields{
          slug
          }
        frontmatter {
          date
          description
          favorite
          published
          title
          tags
        }
      }
    }
  }
  }
`

export default Blog
