// src/pages/Music.vue
<template>
  <Layout>
    <div id="music-page">
      <h1 id="music-title">Music</h1>
      <hr/>
      <div v-for="post in posts" :key="post.title" class="music-post">
          <h3>{{post.title}}</h3>
          <h4>{{post.description}}</h4>
          <div v-html="post.content"/>
      </div>
    </div>
  </Layout>
</template>

<page-query>
query Posts {
  posts: allMusic(filter: { published: { eq: true }}) {
    edges {
      node {
        id
        title
        date
        content
        description
        path
        excerpt
        published
    }
  }
  }
  }
  </page-query>

<script>
import mainImage from "../assets/img/blog_main.jpeg";

export default {
  metaInfo: {
    title: "Nate Spilman | Personal and Professional Website"
  },
  data() {
    return {
      mainImage
    }
  },
  computed:{
    posts(){
      return this.$page.posts.edges.map(edge => edge.node)
    }
  }
};
</script>

<style scoped>
#music-page{
  padding:5rem 2rem;
}

.music-post{
  padding:2rem;
}
</style>

// src/pages/music.tsx
import React from "react"
import { graphql } from "gatsby"
import SEO from "../components/seo"

import Layout from "../components/layout"

const IndexPage = ({ data }) => {
  const { music } = data;
  const songs = music.edges.map(song => song.node)

  return (
    <Layout>
      <SEO title="Nate's Music"/>
      {/* <Title /> */}
    <div id="music-page">
      <h1 id="music-title">Nate's Music</h1>
      <hr/>
      {songs.map(song => (
      <article key="post.title" className="music-post">
        <h3>{song.frontmatter.title}</h3>
        <h4>{song.frontmatter.description}</h4>
      <div dangerouslySetInnerHTML={{ __html: song.html }} />
        </article>
      ))}

    </div>
    </Layout>
  )
}

export const query = graphql`
  query AllMusicPosts {
    music: allMarkdownRemark(
      sort: {fields: frontmatter___date, order: DESC}
    filter: { fields: { collection: { eq: "music" } }}) {
    edges {
      node {
        html
        fields{
          slug
          }
        frontmatter {
          date
          description
          favorite
          published
          title
          tags
        }
      }
    }
  }
  }
`

export default IndexPage
